Blog app - Views
muskan2532150/Blog-app pull request #6
Opened 2022-12-16 18:46 UTC by muskan2532150

- Implement the design from the sneak peek wireframes
- [wireframe1](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_root_users.png)
-  [wireframe2](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_page.png)
- [wireframe3](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_user_all_posts.png)
- [wireframe4](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_single_post.png)
- Use methods in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

2022-12-16 20:37 UTC, codecaiine requested changes
Hi @muskan2532150 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good project setup :heavy_check_mark: 
- No rubocop errors :heavy_check_mark: 

## Required Changes ♻️
- [ ] Please make sure that your project design matches the [wireframe required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#project-requirements) for this project and also make sure that the links and routes taken to the different pages work as expected :+1: 

_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] The link to your licence is broken , please make sure to fix it to make your readme more professional :+1: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 20:37 UTC, codecaiine commented on app/views/users/index.html.erb
> +<li> <%= render 'user',users:users %> </li>
- [ ] According to the project requirement when we click on each, it should take us to their show page. Unfortunately, when I clicked in I could not go to the page I had to type the URLs. Please fix it and also make sure that your design matches with the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_page.png) as require for this project project :+1:

2022-12-16 20:37 UTC, codecaiine commented on app/views/users/show.html.erb
> +</section>
- [ ] Good job so far but make sure that your **See all Post** links open user's post index has a design match with the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png). You design is a bit different. Please fix it as expected for this project :+1:

2022-12-16 20:37 UTC, codecaiine commented on app/views/posts/show.html.erb
> + </section>
- [ ] Good job so far unfortunately I can't go to the post-show page. Please make sure to have a link takes to the post-show page and make sure that it displays the post with all comments listed as shown on  [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png) :+1:

2022-12-17 07:29 UTC, mwanawabangona approved these changes
Hi @muskan2532150,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 13:51 UTC, merged